### ISSUE TITLE
BUG: Tab indicator position only changes on double tap

### ISSUE THREAD

**Issue by ozgecokyasar** [react-native-community/react-native-tab-view#820] opened 2019-06-22 20:28 UTC
http://g.recordit.co/jve9Xh2rdm.gif

The indicator for the active tab does not move when I tap on a tab once. It only moves when I tap on a tab twice.

Environment info
react-native-cli: 2.0.1
react-native: 0.57.1
"react-native-tab-view": "^2.5.0"

#Code
```
import React from 'react';
import { StyleSheet, Dimensions, View } from 'react-native';

import { TabView, SceneMap } from 'react-native-tab-view';



const FirstRoute = () => (
  <View style={[styles.scene, { backgroundColor: '#ff4081' }]} />
);

const SecondRoute = () => (
  <View style={[styles.scene, { backgroundColor: '#673ab7' }]} />
);

const background = (index) => {
  return (
    index % 2 === 0 ?
    'white'
    :
    '#f6f8fa'
  )
}

class Home extends React.Component {
  constructor(props){
    super(props);

    this.state = {
      email: this.props.navigation.state.params.email,
      accessToken: this.props.navigation.state.params.accessToken,
      mantras: this.props.navigation.state.params.mantras,
      visions: this.props.navigation.state.params.visions,
      updated: this.props.navigation.state.params.updated,
      data: this.props.navigation.state.params.data,
      index: 1,
      image: '',
      isReady: false,
      visions: [],
      imagesURLarray: [],

      routes: [
        { key: 'first', title: 'Vision Board' },
        { key: 'second', title: 'Affirm' },
      ],
    }
  }




  render() {
    return (
          <TabView
            navigationState={this.state}
            renderScene={SceneMap({
              first: FirstRoute,
              second: SecondRoute,
            })}
            onIndexChange={index => this.setState({ index })}
            initialLayout={{ width: Dimensions.get('window').width }}
          />
    )
      }
}```

**Comment by thiskevinwang** [comment] 2019-06-23 16:43
Just curious - what if you tried something like:
```js
<TabView
  navigationState={{
    index: this.state.index,
    routes: this.state.routes
  }}
...
```

**Comment by ozgecokyasar** [comment] 2019-06-23 19:55
@thiskevinwang that doesn't work. I literally copied and pasted the whole code in this snack repo and it still doesn't work properly:

https://snack.expo.io/@satya164/react-native-tab-view-quick-start

**Comment by satya164** [comment] 2019-06-27 11:32
Duplicate of #798

**Closed by satya164** 2019-06-27 11:32 UTC
