### ISSUE TITLE
Wierd behavior when used with wix react-native-navigation

### ISSUE THREAD

**Issue by stmkjp** [react-native-community/react-native-tab-view#397] opened 2017-11-22 09:28 UTC
I made 2 tabs, one with webview and another with map component, and put this into wix navigation rootScreen of singleScreenApp.
I also registered another webview to the screen of react native, it shows when I click links in the first root webview in the tab.

it switches between webview and map component without any problem before another screen is pushed in(another webview by link clicking).
But after I click the back button from secondary webview and root screen (with root webview/map in tab view) shows again, tab click no longer works. (view doesn't change)

### Expected behaviour
change to linked route(view) when I click each tabs.

### Actual behaviour
nothing changes. only the first(initial) route shows.
but swiping to next tab is working.

### Code sample, screenshots
in the App.js
```
...
class zapsRMS extends Component {
  constructor(props){
    super(props);
    this.props = props;
  }
  render() {

      return (
      <NodeMain {...this.props}/>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 0,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

Navigation.startSingleScreenApp({
  screen: {
    screen: 'main',
    title: 'MAIN',
      navigatorStyle:{
          navBarBackgroundColor:'#007777',
          navBarTextColor:'white',
          navBarComponentAlignment :'center',
          navBarTitleTextCentered: true
      },
      animationType: 'slide-down'
  }
});
```

MAIN <- root screen
```
...
const initialLayout = {
    height: 0,
    width: Dimensions.get('window').width,
};

export default class NodeMain extends PureComponent{
    ListRoute = () => <NodeList style={[ styles.container, ]} {...this.props}/>;
    MapRoute = () => <NodeMap {...this.props} />;

    constructor(props){
        super(props);

        this.state = {
            index: 0,
            routes: [
                { key: '1', title: 'List' },
                { key: '2', title: 'Map' },
            ],
        };
    }

    _handleIndexChange = index => {
        console.log(this.state)
        this.setState({index});
        console.log(this.state)
    }


    _renderHeader = props => <TabBar {...props} />;

    _renderScene = SceneMap({
        '1': this.ListRoute,
        '2': this.MapRoute,
    });

    render(){
        return(
            <TabViewAnimated
                style={styles.container}
                navigationState={this.state}
                renderScene={this._renderScene}
                renderHeader={this._renderHeader}
                onIndexChange={this._handleIndexChange}

                initialLayout={initialLayout}
            />
        )
    }
}
```

nodelist.js (webview inside tabview) - hooks the message from webpage and pushes another webview

```
export default class NodeList extends Component{

    constructor(props){
        super(props);
        this.receiveMessage = this.receiveMessage.bind(this);
    }
    receiveMessage(event){
        // console.log(this.props);
        let dataCollection = event.nativeEvent.data.split(' ')

        propsToPass = {
            nodeName:dataCollection[0],
            latitude: dataCollection[1],
            longitude: dataCollection[2],
            nodeNum: dataCollection[3]
        }


        this.props.navigator.push({
            screen: 'node.Detail', // unique ID registered with Navigation.registerScreen
            title: dataCollection[0], // navigation bar title of the pushed screen (optional)
            passProps: propsToPass, // Object that will be passed as props to the pushed screen (optional)
            animated: true, // does the push have transition animation or does it happen immediately (optional)
            animationType: 'slide-horizontal', // 'fade' (for both) / 'slide-horizontal' (for android) does the push have different transition animation (optional)
            backButtonTitle: 'BACK', // override the back button title (optional)
            backButtonHidden: false, // hide the back button altogether (optional)
            navigatorStyle: {navBarBackgroundColor:'#007777', navBarTextColor:'white',navBarComponentAlignment :'center',navBarTitleTextCentered: true}, // override the navigator style for the pushed screen (optional)
//            navigatorButtons: {} // override the nav buttons for the pushed screen (optional)
        });
    }

    render(){
        return(
            <WebView
                source={{uri:'http://somepage'}}
                style={{marginTop:0}}
                mixedContentMode="always"
                onMessage={this.receiveMessage}
                automaticallyAdjustContentInsets={false}
            />
        )
    }
}
```

### What have you tried

I checked console.log of this.state value in _handleIndexChange, it seems that state changes well, but it just not trigger re-rendering of view. (why this happen?)

### UPDATE
FYI, I’d downgraded react native version from 0.50.x to 0.49.5 due to webview flickering issue (another wierd behavior but it seems it not related to tab view).

**Comment by stmkjp2** [comment] 2017-11-22 11:45
FYI, I’d downgraded react native version from 0.50.x to 0.49.5 due to webview flickering issue (another wierd behavior but it seems it not related to tab view)

**Comment by azharprabudi** [comment] 2017-11-24 01:31
Hi you can change your code in main / root screen to be here

`export default class NodeMain extends PureComponent{
    ListRoute = () => <NodeList style={[ styles.container, ]} {...this.props}/>;
    MapRoute = () => <NodeMap {...this.props} />;

    constructor(props){
        super(props);
        this.props.navigator.setOnNavigatorEvent(this.handleNavigatorEvent.bind(this));
        this.state = {
            stateTabBar: {
                index: 0,
                routes: [
                    { key: '1', title: 'List' },
                    { key: '2', title: 'Map' },
                ],
            },
            visible: false
        };
    }

    handleNavigatorEvent(event) {
        if (event.id === 'willAppear') {
            this.setState({ visible: true });
        } else if (event.id === 'willDisappear') {
            this.setState({ visible: false });
        }
    }

    _handleIndexChange = index => {
        console.log(this.state)
        this.setState({index});
        console.log(this.state)
    }


    _renderHeader = props => <TabBar {...props} />;

    _renderScene = SceneMap({
        '1': this.ListRoute,
        '2': this.MapRoute,
    });

    render(){
        const { visible } = this.state;
        return(
            <View style={{ flex: visible === true ? 1 : 0 }}
                <TabViewAnimated
                    style={styles.container}
                    navigationState={this.state.stateTabBar}
                    renderScene={this._renderScene}
                    renderHeader={this._renderHeader}
                    onIndexChange={this._handleIndexChange}
                    initialLayout={initialLayout}
                />
            </View>
        )
    }
}`

i solved this problem using this tricks, check this problem at [here](https://github.com/wix/react-native-navigation/issues/1317)

**Comment by satya164** [comment] 2017-11-24 09:01
Duplicate of this https://github.com/react-native-community/react-native-tab-view/issues/225

**Closed by satya164** 2017-11-24 09:01 UTC
