### ISSUE TITLE
Adding view above tab bar

### ISSUE THREAD

**Issue by parthv21** [react-native-community/react-native-tab-view#834] opened 2019-07-09 11:03 UTC
### Current behavior
I tried to wrap the TabView inside another view and it's not rendering correctly. The components flash briefly on the screen, with the scroll position stuck in the middle for the tab view and then most of the components disappear of the screen.

##### Initially I see this:
![IMG_6651](https://user-images.githubusercontent.com/17941287/60882913-754f3580-a266-11e9-9a26-bc2c815317de.PNG)

##### After some jittering arount, it settles on this:
![IMG_6654](https://user-images.githubusercontent.com/17941287/60882594-d9bdc500-a265-11e9-9c28-bb264e205a00.PNG)

### Expected behavior

I want to achieve something like this, and currently I am using **scrollable-tab-view**
![IMG_6649](https://user-images.githubusercontent.com/17941287/60882566-d0345d00-a265-11e9-9bcb-7ae758557aa3.PNG)

![IMG_6650](https://user-images.githubusercontent.com/17941287/60882567-d0ccf380-a265-11e9-92d8-b40a8dadf373.PNG)

### Code sample
I can't share the code as it's a private repo and creating  a snack is difficult since there are many dependencies.

### What have you tried

Initially I had tried to just add the TabView component. But then I tried wrapping it in a view to see if that helped. 

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios
| react-native                 | 0.59.8
| react-native-tab-view        | 2.7.3
| react-native-gesture-handler | 1.2.1
| react-native-reanimated      | 1.0.1
| node                         | 10.15.0
| npm or yarn                  |npm

**Comment by satya164** [comment] 2019-07-09 11:08
> I can't share the code as it's a private repo and creating a snack is difficult since there are many dependencies.

If you can't share the code, I can't help you. Sorry. You need to create a minimal repro with zero deps if you believe this is a bug in the library.

**Comment by parthv21** [comment] 2019-07-09 11:10
I will try to do that. But can TabView be used in the way I am trying to use it? Or it has to be a full-screen component?

**Comment by parthv21** [comment] 2019-07-09 11:11
Because on Android the situation is even weirder.

**Comment by satya164** [comment] 2019-07-09 11:13
@parthv21 it doesn't have to be a full screen component. it should work well anywhere.

**Comment by parthv21** [comment] 2019-07-09 11:18
Okay! I will try to see if I can create a minimal repo.

**Comment by mahdi-gh1373** [comment] 2019-07-22 13:15
Do you solve this problem ? I have this problem too!

```
`const FirstRoute = () => (
  <View style={[styles.scene, { backgroundColor: '#ff4081' }]} />
);
 
const SecondRoute = () => (
  <View style={[styles.scene, { backgroundColor: '#673ab7' }]} />
);

type Props = {};
class Screen1 extends Component<Props> {
  state = {
    index: 0,
    routes: [
      { key: 'first', title: 'First' },
      { key: 'second', title: 'Second' },
    ],
  };


  render() {
    return (
      <View style={styles.container}>
        <View style={{ flex: 1, backgroundColor: '#D62631' }}>
          <TwoPartProgressCircle
              categoryOnePercentage={55}
              categoryOneColor='#D62631'
              categoryTwoPercentage={20}
              categoryTwoColor='#890101'
              spacer={true}
              spacerValue={2}
              text="profile"
              textColor="black"
              textSize={15}
              textWeight="500"
              circleRadius={160}
              distanceFromEdge={3}
              ringWidth={15}
          />  
        </View>
        <View style={{ flex: 1, backgroundColor: '#890101' }}>
          <TabView
            navigationState={this.state}
            renderScene={SceneMap({
              first: FirstRoute,
              second: SecondRoute,
            })}
            onIndexChange={index => this.setState({ index })}
            // initialLayout={{ height: 0 }}
            />          
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  scene: {
    flex: 1,
  },
});
`
```

**Comment by satya164** [comment] 2019-07-22 13:26
@mahdi-gh1373 you have 2 views with `flex: 1` one below another. They'll take the equal height. It's expected behaviour. You should read about flexbox for a better understanding https://css-tricks.com/snippets/css/a-guide-to-flexbox/

I'm closing the issue due to no repro. Please open a new issue with repro if it's a bug with the library.

**Closed by satya164** 2019-07-22 13:26 UTC
Labels: bug

**Comment by Dagger05** [comment] 2020-02-26 05:14
is this a full screen component??? I cant used it as a child component

**Comment by sofianear** [comment] 2020-05-08 21:33
@Dagger05 , @parthv21 
If you're trying to wrap the TabView inside a parent View, just add a style `{{flex: 1}}` to the surrounding view.
