### ISSUE TITLE
How to add a collapsible header

### ISSUE THREAD

**Issue by chenhuaxian** [react-native-community/react-native-tab-view#791] opened 2019-05-30 09:39 UTC

**Comment by tyuwan** [comment] 2019-06-05 04:25
Please let me know if you found a solution.

**Comment by satya164** [comment] 2019-06-27 12:07
closing the issue since it's not a bug in the library. feel free to continue discussing.

**Closed by satya164** 2019-06-27 12:07 UTC

**Comment by zyslife** [comment] 2020-11-02 09:08
@chenhuaxian @tyuwan 
You can try the [react-native-head-tab-view.](https://github.com/zyslife/react-native-head-tab-view)
(tabs with collapsible header)
