### ISSUE TITLE
TabBar is not rendering anything on RN 0.37

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-tab-view#54] opened 2016-10-26 17:37 UTC
![image](https://cloud.githubusercontent.com/assets/2005841/19737307/ae98e64e-9b91-11e6-8db1-95259b6a18de.png)

it is working fine on RN35

this is my code

``` js
_renderLabel = ({ route }) => (
    route.title ? <Text style={styles.tabLabel}>{route.title}</Text> : null
  );

  _renderHeader = (props) => {
    return (
      <TabBarTop
        {...props}
        indicatorStyle={{borderColor: 'green', borderWidth: 1}}
        labelStyle={{color: 'black'}}
        renderLabel={this._renderLabel}
        style={styles.tabbar}
      />
    );
  };
```

styles

``` js
tabLabel: {
    color: 'black',
    margin: 8,
    fontWeight: 'bold',
  },
tabbar:{
    backgroundColor: 'white',
    height: 30,
    borderColor: 'lightgray',
    borderWidth: 1,
    shadowColor: 'rgba(0, 0, 0, 0.12)',
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 2,
    },
  },
```

**Comment by satya164** [comment] 2016-10-27 04:36
That's strange. Do you have an example app which I can quickly try out?

**Comment by Rebsos** [comment] 2016-10-27 16:24
I'm also facing problems with React Native 0.36.0
Nothing renders. If i past the example into my app, the scene renders, but not the tabbar.
RN35 is OK

**Comment by satya164** [comment] 2016-10-28 04:39
@Rebsos I'm gonna try this tonight. Is this on Android or iOS?

**Comment by MatthiasDebaere** [comment] 2016-10-28 09:55
We are having the same issue, both on Android and iOS (tested on multiple devices). No rendering of labels whatsoever, RN version 0.36.0 and react-native-tab-view version 0.0.37.

**Comment by satya164** [comment] 2016-10-28 13:02
I'm looking into it right now. Will keep you updated.

**Comment by satya164** [comment] 2016-10-28 13:23
Hey, when I test with a new example and I don't see the tab bar. I suspect this is due to https://github.com/facebook/react-native/commit/c43a3f5d8412eb0dfe894a192f15efa9c41ab318

You can try putting `height: 48` as a style for the tabbar, it should fix the issue. @MatthiasDebaere @Rebsos 

@Rebsos about the scene not rendering in your app. do you use a scrollview as a scene? in that case, try putting `flex: 1` on the scrollview. If it doesn't work, please link me to an example setup of what you have so I can test.

@sibelius In your case, your label's margin is actually too big to accommodate the text, that's why it's not visible. Try setting margin to a smaller amount or increase the tabbar height.

**Comment by MatthiasDebaere** [comment] 2016-10-28 14:56
> You can try putting height: 48 as a style for the tabbar, it should fix the issue. 
Confirmed, this fixed the issue, thanks!

**Comment by sibelius** [comment] 2016-10-28 15:40
48 as height works, tks for the help

**Comment by satya164** [comment] 2016-10-28 16:07
I'm going to re-open this until I fix it in the lib so you won't have to specify the height.

**Comment by ryankask** [comment] 2016-11-06 07:34
I just upgraded and I'm getting "Invalid prop `overflow` of value `scroll` [...]" on an older version of RN.

**Comment by satya164** [comment] 2016-11-06 11:21
@ryankask Unfortunately I've to drop support for old version of React Native to be able to fix the bug. I wish there was a better way :(

**Comment by ryankask** [comment] 2016-11-06 18:42
Understandable! I'll be upgrading RN soon and I'm sure a lot of users try to keep up to date.

**Comment by Andreyco** [comment] 2016-11-09 12:47
To note, this is still issue on RN 0.37.
Unless I specify tabbar height it's not visible.

**Comment by satya164** [comment] 2016-11-09 13:08
@Andreyco so it broke again then? Hmm... I'll check.

**Comment by Andreyco** [comment] 2016-11-09 13:12
Yes, it is. Top/bottom bars are not visible.

**Comment by Rebsos** [comment] 2016-11-09 19:35
Sorry for responding that late and thank you for your great work.

Yes i'm using a ScrollView and here are my recent tests

React-native + React-native-tab-view
0.36.1 + 0.0.37: working
0.36.1 + 0.0.38: working
0.37.0 + 0.0.37: working
0.37.0 + 0.0.38: working

tested on Android Emulator

**Comment by Andreyco** [comment] 2016-11-09 22:29
Retested on iOS and Android right now - not working.

**Comment by satya164** [comment] 2016-11-10 05:02
Thanks all. I'll check this ASAP.

**Comment by satya164** [comment] 2016-11-11 05:47
Sorry I just tested `0.0.38` in a fresh project with React Native `0.37` and `0.38` on Android and iOS and it's working fine without having to specify height. There's a bug where the hairline shadow in iOS is not visible, but that's a separate thing.

Are you sure you are using correct version? Can you share the example project for me to test?

**Comment by ingvardm** [comment] 2016-11-13 08:17
Im curently using rn 0.37 and tab-view 0.0.38 and it doesn't render.
Worked before with rn 0.35 if  i chenged overflow:'visible' in tabbar.js

**Comment by satya164** [comment] 2016-11-13 14:09
@ingvardm You shouldn't specify any `overflow` value. Try removing `overflow` and lemme know if it still doesn't work.

**Comment by ingvardm** [comment] 2016-11-13 14:32
Works only with rwact-native#0.35 with this modification
`tabbar: {
    backgroundColor: 'black',
    elevation: 4,
    shadowColor: 'black',
    shadowOpacity: 0.1,
    shadowRadius: StyleSheet.hairlineWidth,
    shadowOffset: {
      height: StyleSheet.hairlineWidth,
    },
    zIndex: 1,
    overflow: 'visible',
  },`

**Comment by satya164** [comment] 2016-11-13 14:51
Yes, that's why `react-native-tab-view@0.0.38` doesn't support `react-native@0.35`. You should use `react-native-tab-view@0.0.37` with `react-native@0.35`.

Can you share an example project where the latest version doesn't work with `react-native@0.36` and above when you don't specify any overflow value?

**Comment by ingvardm** [comment] 2016-11-13 14:58
`
import React, { Component } from 'react';
import { View, StyleSheet } from 'react-native';
import { TabViewAnimated, TabBarTop } from 'react-native-tab-view';

import PageExplore from '../pages/Explore';
import PageChats from '../pages/Chats';
import PageEvents from '../pages/Events';

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  page: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default class TabView extends Component {
  state = {
    index: 0,
    routes: [
      { key: '1', title: 'Explore' },
      { key: '2', title: 'Chats' },
      { key: '3', title: 'Events' },
    ],
  };

  _handleChangeTab = (index) => {
    this.setState({ index });
  };

  _renderHeader = (props) => {
    return <TabBarTop {...props} />;
  };

  _renderScene = ({ route }) => {
    switch (route.key) {
    case '1':
      return <PageExplore />;
    case '2':
      return <PageChats />;
    case '3':
      return <PageEvents />;
    default:
      return null;
    }
  };

  render() {
    return (
      <TabViewAnimated
        style={styles.container}
        navigationState={this.state}
        renderScene={this._renderScene}
        renderHeader={this._renderHeader}
        onRequestChangeTab={this._handleChangeTab}
      />
    );
  }
}
`

**Comment by satya164** [comment] 2016-11-13 15:01
@ingvardm I tested with RN 0.36, 0.37 and 0.38 and all were working. What's your version of RN and version of react-native-tab-view?

**Comment by ingvardm** [comment] 2016-11-13 15:04
0.35 + 0.0.37 works with the workaround
Anything else just doesn't render.
Sorry, the repo is private :/

**Comment by satya164** [comment] 2016-11-13 15:07
@ingvardm Can you tell me the exact version of React Native and react-native-tab-view on which you tested so I can try it?

You shouldn't have to specify `overflow: 'visible'` if you're using `react-native@0.35`.

**Comment by ingvardm** [comment] 2016-11-13 15:13
0.37 + 0.0.38/0.0.39 doesn't work
0.35 + 0.0.37 works

**Comment by satya164** [comment] 2016-11-13 15:32
I just tested `react-native@0.37` with `react-native-tab-view@0.0.39` on both Android and iOS with the default example and tabbar is rendering fine for me.

Sorry I cannot debug without a reproducible example. Happy to look into it if anyone can provide me a reproducible example.

**Comment by ingvardm** [comment] 2016-11-15 23:44
Fixed the issue by removing android build.

**Comment by satya164** [comment] 2016-11-17 11:31
I'm closing this. Let me know if someone is still facing the issue.

**Closed by satya164** 2016-11-17 11:31 UTC

**Comment by sibelius** [comment] 2017-04-13 20:14
I'm facing this issue again against react native 43

and "react-native-tab-view": "^0.0.58",

**Comment by sibelius** [comment] 2017-04-13 20:28
fixed using `zIndex: 0`
