### ISSUE TITLE
TabBar style broken

### ISSUE THREAD

**Issue by hustlercoder** [react-native-community/react-native-tab-view#796] opened 2019-06-06 14:46 UTC
# Question

Hi there i have some trouble with the tabbar.
I tried to modify it by adding the style but any imposed style rules are not taken from the library.
For example I tried to change the blue background color but despite the rest of the component applies the changes the tabbar does not record the changes

**Comment by dskusuma** [comment] 2019-06-12 13:56
I have this issue too, but it only affect the Tabbar's text color.

**Comment by dskusuma** [comment] 2019-06-12 14:08
I tried to reinstall the package and now it's working fine. Maybe you can try to reinstall it too? @hustlercoder

**Comment by hustlercoder** [comment] 2019-06-13 08:06
@dskusuma  I've tried but it doesn't always work. many times I had to recreate the app from 0

**Comment by satya164** [comment] 2019-06-13 08:32
Please provide additional info about your environment and a reproducible demo.

**Comment by hustlercoder** [comment] 2019-06-14 07:44
@satya164 I tried the demo code provided by you and it works perfectly. Obviously for the development of our app we have to create a tab bar of different color and with various settings. I tried to change only the color but once changed it doesn't come back. Maybe its a bug only for me but i will try to write a snack to see if the problem reappears . Thank you for now

**Comment by ap050492** [comment] 2019-06-20 12:33
Same issue, Please help me

info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
      Memory: 911.36 MB / 7.89 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

**Comment by Jravvit** [comment] 2019-06-21 04:38
Same problem.

**Comment by hamidfzm** [comment] 2019-06-21 07:38
Same issue here. 

I started a new project. Library seems to ignore styles. Here are my dependencies:

```
  "dependencies": {
    "lodash": "^4.17.11",
    "prop-types": "^15.7.2",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-screens": "^1.0.0-alpha.22",
    "react-native-searchbar": "^1.16.0",
    "react-native-tab-view": "^2.6.1",
    "react-native-vector-icons": "^6.5.0",
    "react-navigation": "^3.11.0",
    "react-navigation-material-bottom-tabs": "^1.0.0"
  }
```

**Comment by satya164** [comment] 2019-06-21 07:54
Can someone provide a repro of what styles are ignored? Confirming the issue isn't very useful. If there's actually a bug, a repro will help pin it down and fix it.

**Comment by hamidfzm** [comment] 2019-06-21 08:29
@satya164 https://github.com/hamidfzm/react-native-tab-view-style-issue

**Comment by hamidfzm** [comment] 2019-06-21 08:36
@satya164 Anything related to style is not working in both Android and iOS. (BTW Sometimes style property backgroundColor works. : ) )

**Comment by satya164** [comment] 2019-06-21 09:04
You're passing the props to `TabView`. You need to pass the props to the tab bar as shown in the docs: https://github.com/react-native-community/react-native-tab-view#tabbar

I'm closing this since it seems to be incorrect usage and not an issue.

**Closed by satya164** 2019-06-21 09:04 UTC
