### ISSUE TITLE
Only renders the initial tab (android only)

### ISSUE THREAD

**Issue by jshumakerpruitt** [react-native-community/react-native-tab-view#172] opened 2017-03-16 11:45 UTC
On android only the initial tab is visible.  By changing `state.index` in the constructor I can make any of my three scenes visible, but when I change tabs, I only get a blank screen.  Works perfectly on iOS.

```javascript
class BusinessScreen extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      index: 2,
      routes: [
        { key: '1', title: 'Home' },
        { key: '2', title: 'Menu' },
        { key: '3', title: 'Contact' }
      ]
    };
  }

  componentDidMount () {
    this.props.businessRequest(this.props.id)
  }

  _handleChangeTab = (index) => {
    this.setState({ index })
  };

  _renderHeader = (props) => {
    return <TabBar {...props} />
  };

  _renderScene = ({ route }) => {
    console.log('route.key: ', route.key)
    switch (route.key) {
      case '1':
        return <BusinessHome business={this.props.business} />
      case '2':
        return <ProductList business={this.props.business} />
      case '3':
        return <BusinessContact business={this.props.business} />
      default:
        return null
    }
  };

  render () {
    console.log(this.state)
    return (
      <View style={[styles.mainContainer, {
        flex: 1,
        backgroundColor: Colors.blueDark
      }]}>
        <TabViewAnimated
          style={{
            flex: 1,
            backgroundColor: Colors.blueDark
          }}
          navigationState={this.state}
          renderScene={this._renderScene}
          renderHeader={this._renderHeader}
          onRequestChangeTab={this._handleChangeTab}
        />
      </View>
    )
  }
}
```

**Comment by maxschmeling** [comment] 2017-03-16 14:56
I just recently started having this same issue. Not sure what has changed. (Using through ex-navigation)

**Comment by karanjthakkar** [comment] 2017-03-19 13:31
Hey @jshumakerpruitt, I created a bare minimum example on Sketch based on the example provided by you: https://sketch.expo.io/r1xkUZnsg 

Have tested this on Android 4.4.4 on a Nexus 7 and on 6.0.0 on a Nexus 5. I'm unable to reproduce this issue. If you can provide any more details for us to help fix this issue for you, that would be great. 

You can also change the code on the Sketch link and give us the updated link if you're able to reproduce your issue over there. Thanks!

**Comment by jshumakerpruitt** [comment] 2017-03-20 01:50
@karanjthakkar Could it be due to `react-native` version?  I do get a yellow box error on the iOS simulator about `keyboardShouldPersistTaps` wanting a boolean value but being given a string(enum).  I'm using 0.39.x.  I'll try downgrading the version of this package.

**Comment by jshumakerpruitt** [comment] 2017-03-23 09:09
Additional info: If I set the tab view screen as my initial screen all tabs work, but if I navigate to the tab view screen from a different screen the problem persists.

**Comment by patrykziem** [comment] 2017-03-24 11:33
I also have encountered this problem on iOS 8. 
It seems that tabs that contain ListView don't render if they are not set as initial. It only renders when the user swipes the screen.

**Comment by maxschmeling** [comment] 2017-03-25 15:05
I was on `react-native@0.38.0` and an upgrade to `react-native@0.38.1` fixed the issue.

**Comment by jshumakerpruitt** [comment] 2017-03-26 06:53
@maxschmeling Worked for me as well. Thanks for the tip!

**Comment by CharlesMangwa** [comment] 2017-03-26 07:33
Thanks @maxschmeling !

**Comment by CharlesMangwa** [comment] 2017-03-26 07:33
Closing #172.

**Closed by CharlesMangwa** 2017-03-26 07:33 UTC

**Comment by Xaber20110202** [comment] 2017-11-02 08:25
https://github.com/react-native-community/react-native-tab-view/issues/243

I used `renderPager={props => <TabViewPagerPan {...props} />}` fixed it
