### ISSUE TITLE
Large number of routes massively drop JS frame rate when switching tabs

### ISSUE THREAD

**Issue by tmmgn** [react-native-community/react-native-tab-view#720] opened 2019-03-19 10:04 UTC
### Current behaviour

TabBar with scroll enabled is laggy and slow on android when using gestures or click on tab even if i render only <View/> inside tab

### Expected behaviour

Expect TabBar with scroll enabled will run smooth as in example

### Code sample

I have used code sample from example:
https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/ScrollableTabBarExample.js

### Screenshots (if applicable)

![lags](https://user-images.githubusercontent.com/11463030/54597020-d8625580-4a46-11e9-831a-05056be9a762.gif)

### What have you tried

Have tried all the optimization tips from the documentation, nothing has chaned. Tried to reduce the number of routes, but lags is still present even with 3 routes

### Your Environment

| software                     | version
| ---------------------------- | -------
| android               |9
| react-native                 |0.59.1
| react-native-tab-view        |2.0.3
| react-native-gesture-handler |1.1.0
| react-native-reanimated      |1.0.0-alpha.12
| node                         |11.0.0
| npm or yarn                  |6.4.1

**Comment by joshperry131** [comment] 2019-03-22 11:38
We also use this in our project and have found the same issue.

I have extracted the ScollableTabBar example and given it 8 tabs instead of 4 to make the behavior obvious in the following gif:
![tabsslow](https://user-images.githubusercontent.com/24830987/54820280-80219280-4c96-11e9-8736-95d4440a4376.gif)

The indicator for which tab is selected lags behind the selected tab buy quite a bit if navigating quickly to a tab a few indexes along via gesture. The scrolling behavior of the tabBar is necessary for our application.

**Comment by tmmgn** [comment] 2019-03-22 11:53
I used this library as temporary workaround for scrollable tabs - https://github.com/ptomasroos/react-native-scrollable-tab-view. Looks pretty fast, give it a try if you need to hurry with your project

**Comment by xaviershay** [comment] 2019-04-10 04:54
I think this might be a dupe of #712

**Comment by xaviershay** [comment] 2019-05-02 04:13
I did what @joshperry131 did above, but pushed it up if anyone else wants to try: https://github.com/xaviershay/react-native-tab-view/tree/720-repro

The problem scales with number of tabs, so drastically increasing the number makes it exceedingly obvious.

**Comment by xaviershay** [comment] 2019-05-02 04:48
I think I've narrowed this down, but I'm not sure how to fix yet.

On tab press, the code [calls a handler](https://github.com/react-native-community/react-native-tab-view/blob/master/src/Pager.js#L313) that is expected to [update the `index` via the state](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/ScrollableTabBarExample.js#L37). This causes a re-render of all scenes, which I believe is causing the pause (source: I added logging statements and saw that it was).

If you swipe, the `onChangeIndex` handler is never called, hence why that avoids this problem.

Using `jumpToIndex` instead (i.e. the other branch of the conditional) works as expected performance wise, though leaves the state incorrect which means subsequent taps don't work properly.

I possible fix may be a `shouldComponentUpdate` somewhere, but I'm not quite sure of the right place nor logic yet.

**Comment by xaviershay** [comment] 2019-05-02 05:16
New insights!

When swiping, there appears to be a similar performance drop but it happens _after_ the tab has switched so is less noticeable. You can see this by toggling the performance inspector - JS frame rate drops to 0 both after swipe change has finished, and also before change from tab press.

**Comment by xaviershay** [comment] 2019-05-02 05:20
Wondering if this is related to new lazy mode, and maybe if there is another regression lurking that's killing PureComponent optimizations:
* Lazy view implementation: https://github.com/react-native-community/react-native-tab-view/commit/a31c3e56c4650790f24c692a3036f481c5004931
* Perf regression fix: https://github.com/react-native-community/react-native-tab-view/commit/9a639037b97e5d60ea6c1896273d169dae3b5b1c

**Comment by satya164** [comment] 2019-05-06 12:12
Can you try this PR and see if it improves the perf for you? https://github.com/react-native-community/react-native-tab-view/pull/764

**Comment by xaviershay** [comment] 2019-05-06 22:05
Thank you! Will give it a go and report back.

**Comment by cani1see** [comment] 2019-05-10 02:09
@satya164  I use master as dependence, nothing changed.

**Comment by xaviershay** [comment] 2019-05-10 02:17
Made some recordings with [my repro](https://github.com/xaviershay/react-native-tab-view/tree/720-repro) rebased against master. I think it got worse sorry :(

iOS: tapping still a little sluggish, new regression around swiping to tab that is off screen.
 
![tab-view](https://user-images.githubusercontent.com/1714/57498028-85f23680-731d-11e9-95a6-f33fe509c2b5.gif)


Android (sorry couldn't get this working on emulator, so recorded with a samsung galaxy): performance of tab tapping just as bad, same regression around swiping to off screen tab introduced but much worse here - 10s of seconds of JS thread at 0fps: [mov recording](https://drive.google.com/file/d/1b6P_czIXe3Q0apNdWdB4yroirSgMKhCc/view?usp=sharing)

**Comment by satya164** [comment] 2019-05-10 12:33
From Safari debugger, these are the method from reanimated are taking most of the time and probably cause the JS frame drops.

![image](https://user-images.githubusercontent.com/1174278/57527636-7a5c3b00-7330-11e9-9d0c-51ed198e6c93.png)

Maybe @kmagiera or @osdnk will know what's happening here.

**Comment by satya164** [comment] 2019-05-14 10:53
Can you try #773 ? The FPS should be improved with that.

**Comment by satya164** [comment] 2019-05-19 15:07
Closing since this should be fixed. Please let me know if you're still facing issues.

**Closed by satya164** 2019-05-19 15:07 UTC

**Comment by xaviershay** [comment] 2019-05-20 00:29
@satya164 can confirm this is fixed. Thank you! 🙏

**Comment by kamleshh-bms** [comment] 2019-10-05 14:52
@satya164 I am facing slow performance issue in RN 0.61 and react navigation-tabs 2.5.5

**Comment by hussainahmad** [comment] 2019-10-25 07:49
I am facing slow performance issue in `expo` version `35.0.0` and `react-native-tab-view` version is `2.10.0`

**Comment by satya164** [comment] 2019-10-25 10:30
Please give more info with code and GIFs.

**Comment by lucasluca** [comment] 2020-02-13 22:32
any solution on this?

**Comment by alexpchin** [comment] 2020-03-06 10:12
Hello, I'm facing a delay on the tabPress (predominantly on Android). This happens with jumpTo or a state change. When swiping, there isn't a delay, only on the tab press.

**Comment by deecewan** [comment] 2020-07-02 06:17
facing the exact same issue as @alexpchin - on android, with 6 tabs, `tabPress` itself runs _very_ quickly (<0.5ms). The action dispatched afterwards seems to be a bit slower

**Comment by anastely** [comment] 2020-09-01 19:35
Hello, Anybody solves this issue?

**Comment by anastely** [comment] 2020-09-01 19:54
> Closing since this should be fixed. Please let me know if you're still facing issues.


Hey, I've faced the same issue, when clicking to any tab as @alexpchin explained
```
"react-native-tab-view": "^2.15.1"
"react-native": "0.63.0",
"react-native-gesture-handler": "^1.6.1",
"react-native-reanimated": "^1.13.0",
```
check here
![Screen-Recording-2020-09-01-at-1](https://user-images.githubusercontent.com/24620979/91899509-e9883c00-eca5-11ea-87e5-ed4c70388ba1.gif)

**Comment by nguyenbathanh** [comment] 2021-12-25 08:44
Did anyone manage to fix the issue?

**Comment by Mohamed-Raid** [comment] 2022-05-04 09:15
+1

**Comment by antstu** [comment] 2022-06-29 20:05
+1

**Comment by Ali-raza365** [comment] 2022-07-04 14:08
+1
