### ISSUE TITLE
Collapsing toolbar with the TabBar

### ISSUE THREAD

**Issue by ashrithks** [react-native-community/react-native-tab-view#258] opened 2017-05-19 12:18 UTC
Hi All,

Tried to achieve collapsing toolbar with tabbar,

 -- ![Valid XHTML](https://camo.githubusercontent.com/97497a24719b85f5d618cba66ac4d23ccfdd7023/687474703a2f2f692e696d6775722e636f6d2f615069333243712e676966)

referring to --  https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e

But no luck!!!
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/19853363/26247388/49bb73c4-3cbb-11e7-8560-de277e711796.gif)

**Comment by CharlesMangwa** [comment] 2017-05-21 19:06
Hi @ashrithks! The article seems to be pretty complete and precise. Without knowing exactly where you made and error, we can't really be of any assistance. I'll suggest you to fork [Janic's example](https://github.com/janicduplessis/react-native-scrollable-header), and modify it step by step until it suits your needs.

**Comment by ashrithks** [comment] 2017-05-22 05:23
Hi @CharlesMangwa  do have any example in react native illustrating the above demo??

**Comment by ashrithks** [comment] 2017-05-22 05:25
And I tried Janic's example,, In that example he has only one parent ScrollView , but in my case , i have a tabview & tabview scene contains two ScrollView

**Comment by CharlesMangwa** [comment] 2017-05-22 09:09
Re-opening so that @ashrithks could send an example of his bug.

**Comment by ashrithks** [comment] 2017-05-22 10:06
Hi @CharlesMangwa ,

Source Code link:-
 https://snack.expo.io/B16Iaee-b

**Comment by ashrithks** [comment] 2017-05-22 10:10
import React, { Component } from 'react';
    import{View, StyleSheet,Animated,
    Platform,
      Dimensions,
    } from 'react-native';
    import { TabViewAnimated, TabBar } from 'react-native-tab-view';
    const HEADER_MAX_HEIGHT = 350;
    const HEADER_MIN_HEIGHT = Platform.OS === 'ios' ? 0 : 0;
    const HEADER_SCROLL_DISTANCE = HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT;
    
    const styles = StyleSheet.create({
      container: {
        flex:1,
      },
      page: {
        height:2000,
        alignItems: 'center',
      },
      header: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        backgroundColor: 'transparent',
        overflow: 'hidden',
        height: HEADER_MAX_HEIGHT,
      },
      backgroundImage: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        width: null,
        height: HEADER_MAX_HEIGHT,
        resizeMode: 'cover',
      },
    });
    
    export default class Homepage extends Component {
      state = {
        index: 0,
        routes: [
          { key: '1', title: 'First' },
           { key: '2', title: 'Second' },
        ],
        scrollY: new Animated.Value(0),
        data:Array.from({ length: 28 }),
        scrollDistance:0,
        scrollDistance2:0
      };
    
      _first: Object;
       _second: Object;
    
      _handleChangeTab = (index) => {
        this.setState({ index });
        switch (index) {
          case '1':
            if (this._first) {
              //this._first._component.scrollTo({ x:0,y: this.state.scrollDistance,animated:true });
            }
            break;
          case '2':
            if (this._second) {
              //this._second._component.scrollTo({ x:0,y: this.state.scrollDistance,animated:true });
            }
            break;
        }
      };
    
      _handleTabItemPress = ({ route }) => {
          if (route !== this.state.routes[this.state.index]) {
            return;
          }
          switch (route.key) {
            case '1':
              if (this._first) {
                //this._first._component.scrollTo({ x:0,y: this.state.scrollDistance,animated:true });
              }
              break;
            case '2':
              if (this._second) {
                //this._second._component.scrollTo({ x:0,y: this.state.scrollDistance,animated:true });
              }
              break;
          }
        };
    
    
      _renderHeader = (props) => {
        return <TabBar {...props}
                  onTabPress={this._handleTabItemPress}/>;
      };
    
      onScroll=(e) =>{
        if(e.nativeEvent.contentOffset.y<=600 ){
          this.setState({scrollDistance:e.nativeEvent.contentOffset.y})
        }
     var windowHeight = Dimensions.get('window').height,
            height = e.nativeEvent.contentSize.height,
            offset = e.nativeEvent.contentOffset.y;
        if( windowHeight + offset >= height ){
         this.setState({data:Array.from({ length: 100 })})
        }
      };
    
      onScroll2=(e) =>{
        if(e.nativeEvent.contentOffset.y<=600 ){
          this.setState({scrollDistance2:e.nativeEvent.contentOffset.y})
        }
     var windowHeight = Dimensions.get('window').height,
            height = e.nativeEvent.contentSize.height,
            offset = e.nativeEvent.contentOffset.y;
        if( windowHeight + offset >= height ){
         this.setState({data:Array.from({ length: 100 })})
        }
      };
    
      _renderScene = ({ route }) => {
        switch (route.key) {
        case '1':
          return(  <Animated.ScrollView
             ref={el => (this._first = el)}
            scrollEventThrottle={1}
            onScroll={Animated.event(
              [{ nativeEvent: { contentOffset: { y: this.state.scrollY } } }],
              {nativeDriver:true,listener: this.onScroll },
            )}>
            <View style={[ styles.page, { backgroundColor: '#ff4081' } ]} />
            </Animated.ScrollView>);
           case '2':
          return(<Animated.ScrollView
            ref={el => (this._second = el)}
            scrollEventThrottle={1}
            onScroll={Animated.event(
              [{ nativeEvent: { contentOffset: { y: this.state.scrollY } } }],
              {nativeDriver:true,listener: this.onScroll2 },
            )}
          >
            <View style= { {backgroundColor: 'teal' , height:2000, } } />
            </Animated.ScrollView>);
        default:
          return null;
        }
      };
    
      render() {
       
    
        const imageOpacity = this.state.scrollY.interpolate({
          inputRange: [0, HEADER_SCROLL_DISTANCE+200 / 2, HEADER_SCROLL_DISTANCE+200],
          outputRange: [1, 1, 0],
          extrapolate: 'clamp',
        });
      
    
        var marTop=HEADER_MAX_HEIGHT;
        if(HEADER_MAX_HEIGHT-(this.state.scrollDistance)>=0){
          marTop=HEADER_MAX_HEIGHT-(this.state.scrollDistance);
        }else if (HEADER_MAX_HEIGHT-(this.state.scrollDistance)<0) {
          marTop=0;
        }
        var marTop2=HEADER_MAX_HEIGHT;
        if(HEADER_MAX_HEIGHT-(this.state.scrollDistance2)>=0){
          marTop2=HEADER_MAX_HEIGHT-(this.state.scrollDistance2);
        }else if (HEADER_MAX_HEIGHT-(this.state.scrollDistance2)<0) {
          marTop2=0;
        }
      
        return (
          <View style={{flex:2,}}>
           <Animated.View
             style={this.state.index==0?
               [
                 styles.header,
                 { height:marTop },
               ]:[
               styles.header,
               { height:marTop2 },
             ]}
           >
             <Animated.Image
               style={[
                 styles.backgroundImage,
                 {
                   opacity: imageOpacity,
                   //transform: [{ translateY: imageTranslate }],
                 },
               ]}
               source={{uri: 'https://az616578.vo.msecnd.net/files/responsive/cover/main/desktop/2016/09/12/636092494089079016-677881086_art.jpg'}}
             />
           </Animated.View>
          <Animated.View style={this.state.index==0?{flex:1,marginTop:marTop,
                                 backgroundColor:'blue',overflow:'hidden',
                                 //transform: [{ translateY: headerTranslateTab }],
                                   //marginBottom:-HEADER_MAX_HEIGHT
                               }
              :{flex:1,marginTop:marTop2,
                                 backgroundColor:'blue',overflow:'hidden',
                                 //transform: [{ translateY: headerTranslateTab }],
                                   //marginBottom:-HEADER_MAX_HEIGHT
                               }}>
          <TabViewAnimated
            style={styles.container}
            navigationState={this.state}
            renderScene={this._renderScene}
            renderHeader={this._renderHeader}
            onRequestChangeTab={this._handleChangeTab}
          />
      </Animated.View>
    </View>
        );
      }
    }

**Comment by satya164** [comment] 2017-05-22 11:07
> And I tried Janic's example,, In that example he has only one parent ScrollView , but in my case , i have a tabview & tabview scene contains two ScrollView

That's upto you to manage. You have access to both scrollviews and the navigation state which tells you which one is in focus. You'll need to figure out how to manage it.

Closing this since it's not a bug with tab view.

**Closed by satya164** 2017-05-22 11:07 UTC
