### ISSUE TITLE
How to custom an overflow tabbar item?

### ISSUE THREAD

**Issue by guoliang1206** [react-native-community/react-native-tab-view#341] opened 2017-09-06 11:22 UTC
The issue like this :
https://github.com/react-community/react-navigation/issues/1154

I have search much more resources, but I can't find a solution,  It works on iOS, but not effective on Android.

**Comment by landmass** [comment] 2017-09-20 09:34
Have you found a solution to the problem?

**Comment by satya164** [comment] 2017-09-20 11:35
Duplicate of #206

**Closed** 2017-09-20 11:35 UTC
