### ISSUE TITLE
[Question] How to implement Collapsible-With-Header-TabView

### ISSUE THREAD

**Issue by Albert0405** [react-native-community/react-native-tab-view#735] opened 2019-04-02 06:04 UTC
I saw your snack example from this link https://snack.expo.io/@satya164/collapsible-header-with-tabview unfortunately this has been implemented on `v0.0.74` of this lib and it seems like `TabViewAnimated` have been removed on the latest version.

My question is how to implement the latest version of this library to achieve `Collapsible-With-Header-TabView`

**Comment by DISKONEKTeD** [comment] 2019-04-05 03:09
Change TabViewAnimated to TabView
Change  renderHeader to renderTabBar

and it should work as you expect it to, unless I forgot something

**Comment by prospegto** [comment] 2019-05-03 16:27
You can use renderTabBar the same way the example is using renderHeader

**Comment by oguzhanali** [comment] 2019-05-03 16:48
and use TabView instead of TabViewAnimated. But there is a static paddingTop problem in scenes, when changing scenes and scrolling. It should be useful having a requested solution to this with updated Collapsible with Header Tab View example on latest version.

**Comment by oguzhanali** [comment] 2019-05-03 16:53
there is an older solution on this, in this repo: https://github.com/austenLacy/react-native-collapsible-header-with-tabs-demo/

**Comment by satya164** [comment] 2019-05-07 10:36
Closing since this is not a bug. Feel free to continue the discussion.

**Closed by satya164** 2019-05-07 10:36 UTC

**Comment by aaveidt** [comment] 2019-10-12 09:03
@oguzhanali 
It doesn't work anymore.
`renderHeader` is missing
#901

**Comment by oguzhanali** [comment] 2019-10-13 11:01
@aaveidt you should use **renderTabBar** instead since v2.0, place your animated header component inside it.

**Comment by zyslife** [comment] 2020-11-02 09:07
@satya164 @oguzhanali @dzpt @prospegto 
You can try the [react-native-head-tab-view.](https://github.com/zyslife/react-native-head-tab-view)
(tabs with collapsible header)
