### ISSUE TITLE
The tab bar button is too delayed when I press the button.

### ISSUE THREAD

**Issue by Frekansapp** [react-native-community/react-native-tab-view#712] opened 2019-03-13 12:25 UTC
### Current behaviour

Version 1.3.2 works without a problem. I tested it in versions 2.0.1 and 2.0.2.  I'm experiencing this problem. When sliding tab's indicator slide out of the screen, tab bar is focused to the active position with a long delay. It is same when navigate throught the tab bar (on press). I think this issue has occurred after the using react-native-gesture-handler and react-native-reanimated. I facing this problem with my LG G4 5.1 device with using this libs expo example and my own project. 

If I swipe over the text input while swiping, it focuses on the text input and turns on the keyboard and swipe does not work (screenshot two). Version 1.3.2 did not have this problem.

### Expected behaviour

Swiping scenes and navigation through tab bar should both work without delay, with same transition speed. 

### Code sample

https://expo.io/@satya164/react-native-tab-view-demos

### Screenshots (if applicable)

<img src="https://media.giphy.com/media/58FXCUWIXUVMyg01Yq/giphy.gif" width="240">
<img src="https://media.giphy.com/media/claGqOcmuoqUpYeTAM/giphy.gif" width="240">

### What have you tried

I updated to version 2.0.1 and started to facing these problems.

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               |Android 5.1
| react-native                 | 0.59.0
| react-native-tab-view        |2.0.2
| react-native-gesture-handler |1.1.0
| react-native-reanimated      |1.0.0-alpha.12
| node                         |11.11.0
| npm or yarn                  |NPM 6.8.0

**Comment by adamsythe** [comment] 2019-03-15 13:50
I had the same problem but I managed to fix it.  

In your onpress of the tabbar, are you changing state or are you calling jumpTo function?  

I was changing state which is sloooow, but when i changed to jumpTo function it started working great!

**Comment by Frekansapp** [comment] 2019-03-15 15:21
> 
> 
> I had the same problem but I managed to fix it.
> 
> In your onpress of the tabbar, are you changing state or are you calling jumpTo function?
> 
> I was changing state which is sloooow, but when i changed to jumpTo function it improved great, still not as fast as their demo app though!

I'm using default example provided by this lib. I don't understand how can i call jumpTo function can you share example?. If the number of operations on the screens is large, the opening time is longer. The demo app is much faster because the screen is blank. Tab bar wait for scenes didCompenentMount, and then sliding animation and focus begins, that makes the delay. Previous versions did not have these problems.

**Comment by adamsythe** [comment] 2019-03-15 15:32
Try this example
https://github.com/react-native-community/react-native-tab-view/tree/master/example

jumpTo function comes in props from renderTabBar

So in my app I have
renderTabBar={this.renderTabBar}

and then
renderTabBar(props) {
    const {
      unreadMessageCounter, screenList,
    } = this.props
    return (
      <TabBar
        {...props}
        unreadMessageCounter={unreadMessageCounter}
        screenList={screenList}
      />
    )
  }

Then my renderTabBar has jumpTo function

**Comment by joshperry131** [comment] 2019-03-22 11:48
Using the scrollableTabBar example as provided produces this behavior. The transition between tabs is too slow.
![tabclick](https://user-images.githubusercontent.com/24830987/54820807-418cd780-4c98-11e9-84b9-f4dc95182716.gif)

**Comment by Frekansapp** [comment] 2019-03-22 14:05
@joshperry131 I have the same problem with or without scrollableTabBar. It has the same behavior even on a blank page but litte bit faster. I also facing [this problem](https://github.com/react-native-community/react-native-tab-view/issues/717#issue-421573957) too.

**Comment by satya164** [comment] 2019-03-22 14:11
The scrollable tab bar is not great on iOS now, but normal tab bar should work fine. @Frekansapp can you open a new issue with a repro? There should be no frame drops or perf issue with the non-scrollable tab bar.

**Comment by Frekansapp** [comment] 2019-03-22 14:24
Okay i will open an new issue with a repo. I found [this issue](https://github.com/react-native-community/react-native-tab-view/issues/693) and it seems have similar problem what i have. Also i'm not on İOS i have only android device. What about [this issue](https://github.com/react-native-community/react-native-tab-view/issues/717#issue-421573957) is there any information can i get ?

**Comment by satya164** [comment] 2019-03-22 14:31
@Frekansapp I haven't had time to check it. It might a bug in react-native-gesture-handler.

**Comment by Frekansapp** [comment] 2019-03-22 15:33
> 
> 
> @Frekansapp I haven't had time to check it. It might a bug in react-native-gesture-handler.

By the way Textinputs are in the Scroolview while this problem happening. It could be an important information when you check it.

**Comment by Bessonov** [comment] 2019-04-03 19:29
After I've copypasted an example code, I had same problem. A reaction on button was incredibly delayed. Two technics make it really fast even on my old nexus 4. The first one is already mentioned here: use `jumpTo` on press. The second one, and it's a good idea for every app, employ practices to avoid rerendering.

**Comment by xaviershay** [comment] 2019-04-10 04:53
I get this on RN 0.58 and react-native-reanimated 1.0.0 also.

**Comment by xaviershay** [comment] 2019-04-10 05:13
> I was changing state which is sloooow, but when i changed to jumpTo function it improved great, still not as fast as their demo app though!

I can't find anything in my app that's specifying custom behaviour for `onTabPress` (though we are using a custom tab bar), and AFAICT the default uses `jumpTo` already: https://github.com/react-navigation/react-navigation-tabs/blob/master/src/utils/createTabNavigator.js#L112

(I'm not sure how to verify that's the right code path yet.)

I don't know if it shows anything, but here is a before/after perf. capture of me pressing tabs as soon as they switch. You can clearly see the regression in the second one:

### Before

<img width="872" alt="perf-before" src="https://user-images.githubusercontent.com/1714/55853132-203a4f80-5ba3-11e9-98bf-c24747f9982c.png">

### After

<img width="1466" alt="perf-after" src="https://user-images.githubusercontent.com/1714/55853144-26c8c700-5ba3-11e9-8b13-feeab6882136.png">

**Comment by scortumee** [comment] 2019-05-10 22:10
> I had the same problem but I managed to fix it.
> 
> In your onpress of the tabbar, are you changing state or are you calling jumpTo function?
> 
> I was changing state which is sloooow, but when i changed to jumpTo function it improved great, still not as fast as their demo app though!

How did you call `jumpTo` function? Should not it be called inside a route? I am using default tabBar ```
renderTabBar={props =>
              <TabBar
                {...props}
                indicatorStyle={{height:4, backgroundColor: '#1077a1' }}
                style={{ backgroundColor: '#F0F0F0'}}
                renderIcon={this.renderIcon}
              />
            }
``` Thank u

**Comment by satya164** [comment] 2019-05-14 20:03
Closing as duplicate of #720

**Closed by satya164** 2019-05-14 20:03 UTC
